modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"

[[mods]]
modId="moreapples"
version="0.1.1"
displayName="MoreApples"
credits="me i did this"
displayURL="https://twitter.com/DiabloDevTwitch"
logoFile="logo.png"
authors="Diablodesu"
description='''
Adds more apples to the game
'''

[[dependencies.moreapples]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




